---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-imagestream-template
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    tags:
    - name: ${OUTPUT_IMAGE_TAG}
      annotations:
      from:
        kind: ${SOURCE_IMAGE_KIND}
        name: ${SOURCE_IMAGE_REGISTRY}${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
      importPolicy:
        scheduled: true
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the objects defined in this template.
  required: true
  value: pdf
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: latest
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: true
  value: DockerImage
- name: SOURCE_IMAGE_REGISTRY
  displayName:  Source Image Registry
  description: The name of the Source Image Registry.
  required: false
  value: docker-remote.artifacts.developer.gov.bc.ca/
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: true
  value: bcgovimages/weasyprint
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: true
  value: latest
